defaults: &defaults
  access_key_id: <%= ENV['AWS_ACCESS_KEY'] %>
  secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  posts_bucket: 'posts.dev.shelleyking.com'

development:
  <<: *defaults

test:
  <<: *defaults
  posts_bucket: 'posts.test.shelleyking.com'

production:
  <<: *defaults
  posts_bucket: 'posts.shelleyking.com'
