# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2166da0ec95a2f463e2f5603499140ef5840e2a318a109b47f34e04784378c26d764e8ecd80fb0f6f8f03e0a39e88cce03d0ff2fc88eb8755c42ec156c118776

test:
  secret_key_base: 510ac6d0a42fc3a078c37b5895b3d55c915723537df92c2108f306b107041256fcaf8214646482bee8f9a342141db13118bd79bc0b17c7438b5f79255ce96f92

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["PRODUCTION_SECRET"] %>
